# Generated by Django 5.0 on 2023-12-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0004_dynamicrelationarealocality_custom_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Area'},
        ),
    ]
