# Generated by Django 5.0 on 2023-12-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0005_alter_area_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locality',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='locality',
            name='sub_locality_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Locality Name'),
        ),
        migrations.AlterUniqueTogether(
            name='locality',
            unique_together={('locality_type', 'sub_locality_name', 'locality_name', 'city')},
        ),
        migrations.DeleteModel(
            name='SubLocality',
        ),
    ]
