# Generated by Django 5.0 on 2023-12-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0008_remove_plot_landmark_remove_plot_street_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together={('plot_no', 'area')},
        ),
        migrations.RemoveField(
            model_name='plot',
            name='building',
        ),
    ]
