# Generated by Django 5.0 on 2024-02-10 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0010_rename_building_name_building_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='app_address.district', verbose_name='district'),
        ),
        migrations.AddField(
            model_name='locality',
            name='tehsil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='app_address.tehsil', verbose_name='tehsil'),
        ),
    ]
