# Generated by Django 5.0 on 2024-02-10 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0012_rename_dynamicrelationarealocality_arealocalityrelationship_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='address',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='app_address.plot', verbose_name='plot'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='app_address.building', verbose_name='building'),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='app_address.floor', verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='address',
            name='unit_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='app_address.unit', verbose_name='unit'),
        ),
        migrations.RemoveField(
            model_name='address',
            name='plot_no',
        ),
    ]
