# Generated by Django 5.0 on 2024-02-28 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0014_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLocality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_address.area')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_address.locality')),
            ],
            options={
                'unique_together': {('area', 'locality')},
            },
        ),
        migrations.AddField(
            model_name='area',
            name='localities',
            field=models.ManyToManyField(through='app_address.AreaLocality', to='app_address.locality', verbose_name='localities'),
        ),
    ]
