# Generated by Django 5.0 on 2024-02-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0015_arealocality_area_localities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaLocalityRelationship',
        ),
    ]
