# Generated by Django 5.0 on 2024-02-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0016_delete_arealocalityrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='locality_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='app_address.localitytype', verbose_name='locality Type'),
        ),
    ]
