# Generated by Django 5.0 on 2024-03-04 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0019_area_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tower',
            options={'verbose_name': 'Tower', 'verbose_name_plural': 'Tower'},
        ),
        migrations.AddField(
            model_name='building',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building', to='app_address.area', verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot', to='app_address.area', verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='block',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('name', 'area')},
        ),
        migrations.AlterUniqueTogether(
            name='floorplotrelationship',
            unique_together={('plot', 'floor')},
        ),
        migrations.AlterUniqueTogether(
            name='floortowerrelationship',
            unique_together={('floor', 'tower')},
        ),
        migrations.AlterUniqueTogether(
            name='landmarkbuildingrelationship',
            unique_together={('building', 'landmark')},
        ),
        migrations.AlterUniqueTogether(
            name='landmarkplotrelationship',
            unique_together={('plot', 'landmark')},
        ),
        migrations.AlterUniqueTogether(
            name='tower',
            unique_together={('name', 'block')},
        ),
    ]
