# Generated by Django 5.0 on 2024-03-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0021_alter_building_area_alter_plot_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='building',
        ),
        migrations.RemoveField(
            model_name='address',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='address',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='address',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='address',
            name='unit_no',
        ),
        migrations.RemoveField(
            model_name='address',
            name='updated_by',
        ),
    ]
