# Generated by Django 5.0 on 2024-03-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0022_remove_address_building_remove_address_created_by_and_more'),
        ('app_property', '0003_remove_property_area_in_sq_ft_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
