# Generated by Django 5.0 on 2024-03-05 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0024_alter_area_created_by_alter_area_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='app_address.city', verbose_name='city'),
        ),
    ]
